# Generated by Django 5.2.3 on 2025-06-29 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('job_id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=50)),
                ('gender_requirement', models.CharField(max_length=50)),
                ('experience_min', models.PositiveIntegerField()),
                ('experience_max', models.PositiveIntegerField()),
                ('experience_level', models.CharField(max_length=50)),
                ('salary_type', models.CharField(max_length=50)),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('location_type', models.CharField(max_length=50)),
                ('full_location_address', models.CharField(max_length=255)),
                ('map_location', models.JSONField(help_text='{"lat": 27.7, "lng": 85.3}')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='authentication.employer')),
            ],
            options={
                'verbose_name': 'Job Post',
                'verbose_name_plural': 'Job Posts',
                'ordering': ['-posted_at'],
            },
        ),
    ]
