# Generated by Django 5.2.3 on 2025-06-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='num_candidates_required',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
