# Generated by Django 5.2.3 on 2025-06-30 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0002_jobpost_num_candidates_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='map_location',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='admin_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
