# Generated by Django 5.2.3 on 2025-06-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0003_remove_jobpost_map_location_jobpost_admin_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='map_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
