# Generated by Django 5.2.3 on 2025-06-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0004_jobpost_map_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='salary_frequency',
            field=models.CharField(default='monthly', max_length=20),
            preserve_default=False,
        ),
    ]
