# Generated by Django 5.2.3 on 2025-07-01 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_employer'),
        ('employer_profile', '0005_jobpost_salary_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('sub_industry', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(max_length=50)),
                ('founded_date', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='company_banners/')),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='authentication.employer')),
            ],
        ),
    ]
