# Generated by Django 5.2.3 on 2025-07-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0006_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='founded_date',
            field=models.DateField(null=True),
        ),
    ]
