# Generated by Django 5.2.3 on 2025-07-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0007_alter_companyprofile_founded_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='sub_industry',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='tagline',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='address',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
