# Generated by Django 5.2.3 on 2025-07-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0008_rename_phone_companyprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
