# Generated by Django 5.2.3 on 2025-07-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0009_alter_companyprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='company_certificates/'),
        ),
    ]
