# Generated by Django 5.2.3 on 2025-07-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0010_companyprofile_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='certificate_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
