# Generated by Django 5.2.3 on 2025-07-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0012_employerpremium'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerpremium',
            name='subscription_price',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
