# Generated by Django 5.2.3 on 2025-07-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0013_employerpremium_subscription_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerpremium',
            name='subscription_price',
        ),
    ]
