# Generated by Django 5.2.3 on 2025-07-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_employer_is_verified'),
        ('employer_profile', '0011_companyprofile_certificate_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='authentication.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer_profile.jobpost')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
