# Generated by Django 5.2.3 on 2025-07-03 22:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employer_is_verified'),
        ('candidate_profile', '0001_initial'),
        ('employer_profile', '0011_companyprofile_certificate_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewing', 'Under Review'), ('interview', 'Interview Scheduled'), ('offered', 'Offer Extended'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('interview_at', models.DateTimeField(blank=True, null=True)),
                ('cover_letter', models.FileField(upload_to='applications/cover_letters/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'png', 'jpg', 'jpeg'])])),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='authentication.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employer_profile.jobpost')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
