# Generated by Django 5.2.3 on 2025-07-04 09:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employer_is_verified'),
        ('candidate_profile', '0002_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'png', 'jpg', 'jpeg'])])),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to='authentication.candidate')),
            ],
        ),
    ]
