# Generated by Django 5.2.3 on 2025-07-04 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_profile', '0003_candidatecv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecv',
            name='parsed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
