# Generated by Django 5.2.3 on 2025-07-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_profile', '0004_alter_candidatecv_parsed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='meeting_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
