# Generated by Django 5.2.3 on 2025-07-07 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_candidate_profile_picture'),
        ('candidate_profile', '0005_jobapplication_meeting_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=False)),
                ('subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('payment_ok', models.BooleanField(default=False)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium', to='authentication.candidate')),
            ],
        ),
    ]
